# 服务配置
server:
  # 运行端口
  port: 8080
  servlet:
    # 编码
    encoding:
      # 开启编码
      enabled: true
      # 强制使用charset
      force: true
      charset: UTF-8

# spring配置
spring:
  application:
    name: reading
  # 环境配置
  profiles:
    active: prod
  # mysql配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${reading.mysql.host}:3306/reading?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&characterEncoding=utf-8
    username: root
    password: ${reading.mysql.password}
  data:
    # redis配置
    redis:
      host: ${reading.redis.host}
      password: ${reading.redis.password}
      port: 6379
  # rabbitmq配置
  rabbitmq:
    host: ${reading.rabbitmq.host}
    port: 5672
    virtual-host: /
    username: root
    password: ${reading.rabbitmq.password}
  # 邮件配置
  mail:
    host: ${MAIL_HOST} # 邮件服务器,例如  smtp.qq.com
    username: ${MAIL_USERNAME} # 邮箱
    password: ${MAIL_PASSWORD} # 授权码
    ssl:
      enabled: true

# mybatis-plus配置
mybatis-plus:
  # xml映射文件路径
  mapper-locations: classpath:mapper/**/*.xml
  # 类型别名包
  type-aliases-package: com.reading.domain.po
  configuration:
    # 日志实现类
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 驼峰 -> 下划线
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      # 主键策略, 自动递增
      id-type: auto

# knife4j的增强配置，不需要增强可以不配
knife4j:
  # 开启增强
  enable: true
  # 当前是否是生产环境
  production: ${reading.knife4j.production}
  setting:
    language: zh_cn # 语言

# 日志配置
logging:
  level: # 日志级别
    com.reading: debug
  file: # 日志目录位置
    path: logs
  pattern: # 日期格式
    dateformat: yyyy-MM-dd HH:mm:ss

# 项目配置
reading:
  # JWT 令牌配置
  jwt:
    token-name: token
    secret-key: secretKey
    ttl: 86400
  # 阿里云 服务配置
  aliyun:
    accessKeyId: ${ALIBABA_CLOUD_ACCESS_KEY_ID}
    accessKeySecret: ${ALIBABA_CLOUD_ACCESS_KEY_SECRET}
