# 服务配置
server:
  # 运行端口
  port: 8080
  servlet:
    # 编码
    encoding:
      # 开启编码
      enabled: true
      # 强制使用charset
      force: true
      charset: UTF-8

# spring配置
spring:
  # mysql配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://reading-mysql:3306/reading?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  data:
    # redis配置
    redis:
      host: reading-redis
      password: 123456
      port: 6379
      database: 0
  # rabbitmq配置
  rabbitmq:
    host: reading-rabbitmq
    port: 5672
    virtual-host: /reading-rabbitmq
    username: rabbitmq
    password: rabbitmq

# mybatis-plus配置
mybatis-plus:
  # xml映射文件路径
  mapper-locations: classpath:mapper/**/*.xml
  # 类型别名包
  type-aliases-package: com.reading.domain.po
  configuration:
    # 日志实现类
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 驼峰 -> 下划线
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      # 主键策略, 自动递增
      id-type: auto

# springdoc-openapi项目配置
springdoc:
  # 设置默认分组
  swagger-ui:
    # 文档路径
    path: /swagger-ui.html
    # 如果需要对接口进行排序
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  # 扫描路径
  packages-to-scan: com.reading.server.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  # 开启增强
  enable: true
  # 生产环境关闭
  production: false
  # 开启Basic认证（可选）
  basic:
    enable: false
    username: admin
    password: 123456
  setting:
    # 语言
    language: zh_cn

# 项目配置
reading:
  jwt:
    token-name: token
    secret-key: secretKey
    ttl: 86400
