reading:
    mysql:
        host: localhost
        database: reading
        username: root
        password: 123456
    redis:
        host: localhost
        password: 123456
        port: 6379
    rabbitmq:
        host: localhost
        port: 5672
        username: rabbitmq
        password: rabbitmq
