version: '3.8'

name: reading

services:
    nginx:
        image: nginx:1.25-alpine
        container_name: reading-nginx
        ports:
            - '80:80'
        volumes:
            - ./conf.d:/etc/nginx/conf.d:ro
            - ./dist:/usr/share/nginx/html/dist:ro
            - ./logs:/var/log/nginx
        environment:
            - TZ=Asia/Shanghai
        networks:
            - reading

networks:
    reading:
