# 名称
name: Deploy to Nginx

# 触发条件
on:
  push: # 当有代码推送到指定分支时触发
    branches:
      - main
      - master
    paths: # 当指定路径下的文件有变更时触发
      - "reading-ui/**"
  workflow_dispatch: # 手动触发

# 需要执行的任务
jobs:
  # 任务名称 (构建)
  build-deploy:
    # 运行环境
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: reading-ui # 指定工作目录

    # 任务步骤
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装 pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: 安装依赖
        run: pnpm install

      - name: 构建项目
        run: pnpm build

      - name: 打包构建产物
        run: |
          mkdir -p deploy
          mv ./dist/ ./deploy
          mv ./conf.d/ ./deploy
          mv ./docker-compose.yml ./deploy
          tar -czvf deploy.tar.gz ./deploy
          ls -al

      - name: 上传到服务器
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: reading-ui/deploy.tar.gz
          target: /home

      - name: 部署到服务器
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home
            rm -rf reading-ui
            tar -xzvf deploy.tar.gz
            mv deploy reading-ui
            cd reading-ui
            docker compose up -d nginx
            docker compose restart nginx
