# 名称
name: Deploy to Nginx

# 触发条件
on:
  push: # 当有代码推送到指定分支时触发
    branches:
      - main
      - master
    paths:
      - "reading-ui/**"
  workflow_dispatch: # 手动触发

# 需要执行的任务
jobs:
  # 任务名称 (构建)
  build-deploy:
    # 运行环境
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: reading-ui # 指定工作目录

    # 任务步骤
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装 pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: 安装依赖
        run: pnpm install

      - name: 构建项目
        run: pnpm build

      - name: 看看
        run: ls -al

      - name: 打包构建产物和nginx配置文件
        run: tar -czvf reading-ui.tar.gz ./dist ./nginx.conf

      - name: 看看
        run: tar -tvf reading-ui.tar.gz
