# 名称
name: Deploy to Nginx

# 触发条件
on:
  push: # 当有代码推送到指定分支时触发
    branches:
      - main
      - master
    paths: # 当指定路径下的文件有变更时触发
      - "reading-ui/**"
  workflow_dispatch: # 手动触发

# 需要执行的任务
jobs:
  # 任务名称 (构建)
  build:
    # 运行环境
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: reading-ui # 指定工作目录

    # 任务步骤
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装 pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: 安装依赖
        run: pnpm install

      - name: 构建项目
        run: pnpm build

      - name: 打包构建产物
        run: |
          mkdir -p reading-ui
          mv ./dist/ ./reading-ui
          mv ./conf.d/ ./reading-ui
          mv ./docker-compose.yaml ./reading-ui
          tar -czvf reading-ui.tar.gz ./reading-ui

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: reading-ui
          path: ./reading-ui/reading-ui.tar.gz

  deploy:
    # 运行环境
    runs-on: ubuntu-latest
    # 依赖任务
    needs: build

    # 任务步骤
    steps:
      - name: 下载构建产物
        uses: actions/download-artifact@v4
        with:
          name: reading-ui
          path: .

      - name: 上传到服务器
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: reading-ui.tar.gz
          target: /root/workspace/

      - name: 部署
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.SERVER_IP }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /root/workspace/
            rm -rf reading-ui
            tar -xzvf reading-ui.tar.gz
            cd reading-ui
            docker compose up -d nginx
            docker compose restart nginx
